import type { INodeProperties } from 'n8n-workflow';

export const chatProperties: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['chat'] } },
		default: 'getInfo',
		options: [
			{ name: 'Block User', value: 'blockUser', action: 'Block a chat member' },
			{ name: 'Delete Members', value: 'deleteMembers', action: 'Remove selected chat members' },
			{ name: 'Get Admins', value: 'getAdmins', action: 'Get chat administrators' },
			{ name: 'Get Blocked Users', value: 'getBlockedUsers', action: 'Get blocked chat users' },
			{ name: 'Get Info', value: 'getInfo', action: 'Get chat info' },
			{ name: 'Get Members', value: 'getMembers', action: 'Get a page of chat members' },
			{ name: 'Get Pending Users', value: 'getPendingUsers', action: 'Get pending chat users' },
			{ name: 'Pin Message', value: 'pinMessage', action: 'Pin a chat message' },
			{
				name: 'Resolve Pending',
				value: 'resolvePending',
				action: 'Approve or reject join requests',
			},
			{ name: 'Send Actions', value: 'sendActions', action: 'Send or clear chat activity' },
			{ name: 'Set About', value: 'setAbout', action: 'Set the chat description' },
			{ name: 'Set Avatar', value: 'setAvatar', action: 'Set the chat avatar' },
			{ name: 'Set Rules', value: 'setRules', action: 'Set chat rules' },
			{ name: 'Set Title', value: 'setTitle', action: 'Set the chat title' },
			{ name: 'Unblock User', value: 'unblockUser', action: 'Unblock a chat user' },
			{ name: 'Unpin Message', value: 'unpinMessage', action: 'Unpin a chat message' },
		],
	},
	{
		displayName: 'Chat ID',
		name: 'chatId',
		type: 'string',
		default: '',
		required: true,
		displayOptions: { show: { resource: ['chat'] } },
	},
	{
		displayName:
			'Chat permissions are checked by VK Teams. Use a test chat for moderation and other changes.',
		name: 'chatPermissions',
		type: 'notice',
		default: '',
		displayOptions: { show: { resource: ['chat'] } },
	},
	{
		displayName: 'Cursor',
		name: 'cursor',
		type: 'string',
		default: '',
		description:
			'Leave empty for the first page. Pass the previous response cursor to read the next page; this operation returns one page.',
		displayOptions: { show: { resource: ['chat'], operation: ['getMembers'] } },
	},
	{
		displayName: 'Members (JSON)',
		name: 'members',
		type: 'json',
		default: '[]',
		required: true,
		description:
			'Nonempty JSON array of user ID strings to remove, for example ["user@example.com"]. Expressions can return an array. This removes users without blocking them.',
		displayOptions: { show: { resource: ['chat'], operation: ['deleteMembers'] } },
	},
	{
		displayName: 'User ID',
		name: 'userId',
		type: 'string',
		default: '',
		required: true,
		displayOptions: { show: { resource: ['chat'], operation: ['blockUser', 'unblockUser'] } },
	},
	{
		displayName: 'User ID',
		name: 'userId',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: { resource: ['chat'], operation: ['resolvePending'], everyone: [false] },
		},
	},
	{
		displayName: 'Delete Last Messages',
		name: 'delLastMessages',
		type: 'boolean',
		default: false,
		description: 'Whether to also delete the blocked user’s recent messages',
		displayOptions: { show: { resource: ['chat'], operation: ['blockUser'] } },
	},
	{
		displayName: 'Everyone',
		name: 'everyone',
		type: 'boolean',
		default: false,
		description: 'Whether to process all pending join requests instead of one explicit user',
		displayOptions: { show: { resource: ['chat'], operation: ['resolvePending'] } },
	},
	{
		displayName: 'Approve',
		name: 'approve',
		type: 'boolean',
		default: false,
		description:
			'Whether to approve the selected join requests. If disabled, the requests are rejected.',
		displayOptions: { show: { resource: ['chat'], operation: ['resolvePending'] } },
	},
	{
		displayName: 'Actions',
		name: 'actions',
		type: 'multiOptions',
		default: ['typing'],
		options: [
			{ name: 'Looking', value: 'looking' },
			{ name: 'Typing', value: 'typing' },
		],
		description: 'Activity indicators to send. Select no actions to clear the indicators.',
		displayOptions: { show: { resource: ['chat'], operation: ['sendActions'] } },
	},
	{
		displayName: 'Title',
		name: 'title',
		type: 'string',
		default: '',
		required: true,
		description: 'New nonempty chat title',
		displayOptions: { show: { resource: ['chat'], operation: ['setTitle'] } },
	},
	{
		displayName: 'About',
		name: 'about',
		type: 'string',
		default: '',
		description: 'Chat description. Leave empty to clear it.',
		displayOptions: { show: { resource: ['chat'], operation: ['setAbout'] } },
	},
	{
		displayName: 'Rules',
		name: 'rules',
		type: 'string',
		default: '',
		description: 'Chat rules. Leave empty to clear them.',
		displayOptions: { show: { resource: ['chat'], operation: ['setRules'] } },
	},
	{
		displayName: 'Message ID',
		name: 'msgId',
		type: 'string',
		default: '',
		required: true,
		description: 'Message ID as a string to preserve large numeric IDs',
		displayOptions: { show: { resource: ['chat'], operation: ['pinMessage', 'unpinMessage'] } },
	},
	{
		displayName: 'Input Binary Field',
		name: 'binaryPropertyName',
		type: 'string',
		default: 'data',
		required: true,
		description: 'Binary field containing the avatar image to upload',
		displayOptions: { show: { resource: ['chat'], operation: ['setAvatar'] } },
	},
];
